### ISSUE TITLE
invalid request descriptor after setup completed

### ISSUE THREAD

**Issue by sandrobonazzola** [containers/qm#103]
On a clean CentOS Stream 9 minimal VM I setup qm.

I can see it up:
```console
# podman exec -ti qm ps -eZ
LABEL                               PID TTY          TIME CMD
system_u:system_r:qm_t:s0             1 ?        00:00:00 systemd
system_u:system_r:qm_t:s0            24 ?        00:00:00 systemd-journal
system_u:system_r:qm_t:s0            33 ?        00:00:00 hirte-agent
system_u:system_r:qm_t:s0            34 ?        00:00:00 systemd-logind
system_u:system_r:qm_t:s0            36 ?        00:00:00 dbus-broker-lau
system_u:system_r:qm_t:s0            37 ?        00:00:00 dbus-broker
system_u:system_r:qm_t:s0           161 pts/0    00:00:00 ps
```

I followed the demo steps and imported the quadlet for running httpd container within qm.

My host has hostname `centos9.home` and the setup created :
```console
# cat /usr/lib/qm/rootfs/etc/hirte/agent.conf
[hirte-agent]
NodeName=qm.centos9.home
```

On the host I have:
```console
# cat /etc/hosts 
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

# hostname
centos9.home
```

When I try to run the quadlet I have:
```console
# hirtectl restart qm.centos9.home myquadlet.service
Failed to issue method call: Unknown object '/org/containers/hirte/node/qm_2ecentos9_2ehome'.
Call to manager failed: Invalid request descriptor
```

I think some configuration is missing on the host as I don't see any configuration for telling the manager where to look for `qm.centos9.home`:
```console
# ls -R /etc/hirte/
/etc/hirte/:
agent.conf.d  hirte.conf.d

/etc/hirte/agent.conf.d:
README.md

/etc/hirte/hirte.conf.d:
README.md
```

**Comment by sandrobonazzola** [comment]
Something like:
```console
# cat /etc/hirte/hirte.conf.d/00-allowed-nodes.conf 
[hirte]
AllowedNodeNames=qm.centos9.home
```
worked for me

**Comment by dougsland** [comment]
> Something like:
> 
> ```
> # cat /etc/hirte/hirte.conf.d/00-allowed-nodes.conf 
> [hirte]
> AllowedNodeNames=qm.centos9.home
> ```
> 
> worked for me

That's correct @sandrobonazzola, it's required to set the allowedNodeNames to hirte allow communication with the specific agent.

**Comment by dougsland** [comment]
@sandrobonazzola is everything working now?

**Comment by sandrobonazzola** [comment]
It works for me now, but I would have expected `/usr/share/qm/setup` to take care of that as it also configured `/usr/lib/qm/rootfs/etc/hirte/agent.conf` ;
I was looking at  https://github.com/containers/qm/blob/main/demos/demo#L83 code in order to reproduce on my system.

**Comment by dougsland** [comment]
> It works for me now, but I would have expected `/usr/share/qm/setup` to take care of that as it also configured
> `/usr/lib/qm/rootfs/etc/hirte/agent.conf` ; I was looking at https://github.com/containers/qm/blob/main/demos/demo#L83 
> code in order to reproduce on my system.

I understood your point. @rhatdan improve setup or add few lines in README.md ?

@sandrobonazzola We also have others tools for testing (the same as e2e uses) we would appreciate inputs for improvements:
https://github.com/containers/qm/tree/main/tests/e2e (similar to demo)
https://github.com/containers/qm/tree/main/tests/e2e/dashboard-tui

**Comment by rhatdan** [comment]
You think the setup script should add the entry to /etc/hirte/hirte.conf, seems reasonable to me.

**Comment by rhatdan** [comment]
@dougsland could you make that change?

**Comment by dougsland** [comment]
> @dougsland could you make that change?

sure

**Comment by dougsland** [comment]
just an update, I am working in the hirte config load from sources, as soon I finish there, I will get back here. It's not urgent, as it has workaround.

**Comment by dougsland** [comment]
ok, back to this task, let me check what's going on.
