### ISSUE TITLE
[RFE] list-nodes command

### ISSUE THREAD

**Issue by sandrobonazzola** [containers/qm#104]
I think a `list-nodes` command that can show the nodes known to `hirte` would be very useful.

**Comment by sandrobonazzola** [comment]
sorry, opened in the wrong repo, can you please transfer this to hirte repo?

**Comment by dougsland** [comment]
Hey @sandrobonazzola, you will need to open an issue in the hirte repo. Feel free to point https://github.com/containers/hirte/issues/291 too. It might help to get it back on the list (even "similar" to connection status thing).
