### ISSUE TITLE
no validation of command line parameters

### ISSUE THREAD

**Issue by sandrobonazzola** [containers/qm#114]
`setup` does assume to get always valid parameters without any validation:

```bash
INSTALLDIR="$1"
[ -n "${INSTALLDIR}" ] || INSTALLDIR=/usr/share/qm

ROOTFS="$2"
[ -n "${ROOTFS}" ] || ROOTFS=/usr/lib/qm/rootfs
```

ending up with situations like: `/usr/share/qm/setup --help`

finishing with errors like:

```console
cp: unrecognized option '--help/containers.conf'
Try 'cp --help' for more information.
```

**Comment by rhatdan** [comment]
setup was not considered a general use script, we can fix a few of these, but I don't think we should look at this as a script that the general user will be executing.

**Comment by dougsland** [comment]
> setup was not considered a general use script, we can fix a few of these, but I don't think we should look at this as a script that the general user will be executing.

Agreed, I can take this @rhatdan to quick resolve it.

**Comment by rhatdan** [comment]
SGTM
