### ISSUE TITLE
[spec] qm rootfs removal on qm package update

### ISSUE THREAD

**Issue by sandrobonazzola** [containers/qm#142]
Running a `dnf update qm` I noticed:

```console
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                     1/1 
  Upgrading        : qm-0.4.1-2.noarch                                                                                                                                   1/2 
  Running scriptlet: qm-0.4.1-2.noarch                                                                                                                                   1/2 
  Cleanup          : qm-0.4.1-1.el9iv.noarch                                                                                                                             2/2 
warning: directory /usr/lib/qm/rootfs: remove failed: Device or resource busy

  Running scriptlet: qm-0.4.1-1.el9iv.noarch                                                                                                                             2/2 
  Verifying        : qm-0.4.1-2.noarch                                                                                                                                   1/2 
  Verifying        : qm-0.4.1-1.el9iv.noarch                                                                                                                             2/2 

Upgraded:
  qm-0.4.1-2.noarch                     
```

We recommend to have `/usr/lib/qm/rootfs` on its own filesystem so it's not being removed being a mounted mount point.
But this is wrong, qm shouldn't try to remove the qm rootfs (at least not during an upgrade!)

The issue seems to be in `%file` section:
```lua
%ghost %dir %{_installscriptdir}/rootfs
%ghost %{_installscriptdir}/rootfs/*
```

If there's no good reason to ghost those paths I would suggest to just remove those 2 lines from the spec file.

**Comment by dougsland** [comment]
looks sane to me, @lsm5 could you please share your thoughts?

**Comment by lsm5** [comment]
IIRC, we had not considered the case of package upgrade earlier. @rhatdan PTAL

**Comment by rhatdan** [comment]
If you run the setup script a second time it will update the rootfs.

**Comment by rhatdan** [comment]
So I agree they should be ghosted.

**Comment by dougsland** [comment]
@sandrobonazzola we have a green light, would you like to send a patch ? If you are busy, I can take care of.

**Comment by sandrobonazzola** [comment]
> @sandrobonazzola we have a green light, would you like to send a patch ? If you are busy, I can take care of.

I can prepare a patch

**Comment by sandrobonazzola** [comment]
After digging into it a bit more, the issue is that in the package provided within the repos, as in copr, we have:
```lua
%global _installscriptdir %{_prefix}/lib/qm
```

while in the spec file included in this git repo we have:
```lua
%global _installscriptdir %{_prefix}/%{_lib}/%{modulenames}
```
which resolves to `/usr/lib64/qm` instead of `/usr/lib/qm` 
```

**Comment by sandrobonazzola** [comment]
So, question is: do we want to use `%{_lib}` and update the docs to point to `/usr/lib64/qm` or do we want to keep `/usr/lib/qm` and ignore rpmlint `qm.spec:8: E: hardcoded-library-path in %{_prefix}/lib/%{modulenames}`?

**Comment by lsm5** [comment]
So looking at 

> So, question is: do we want to use `%{_lib}` and update the docs to point to `/usr/lib64/qm` or do we want to keep `/usr/lib/qm` and ignore rpmlint `qm.spec:8: E: hardcoded-library-path in %{_prefix}/lib/%{modulenames}`?

@sandrobonazzola just to confirm, `/usr/lib/qm` is giving you the rpmlint error? I don't see that myself on the file from dist-git:

```
$ rpm -q rpmlint
rpmlint-2.4.0-6.fc38.noarch

$ rpmlint qm.spec 
==================================================================================================================================================== rpmlint session starts ===================================================================================================================================================
rpmlint: 2.4.0
configuration:
    /usr/lib/python3.11/site-packages/rpmlint/configdefaults.toml
    /etc/xdg/rpmlint/fedora-legacy-licenses.toml
    /etc/xdg/rpmlint/fedora-spdx-licenses.toml
    /etc/xdg/rpmlint/fedora.toml
    /etc/xdg/rpmlint/scoring.toml
    /etc/xdg/rpmlint/users-groups.toml
    /etc/xdg/rpmlint/warn-on-functions.toml
checks: 31, packages: 1

===================================================================================================================== 0 packages and 1 specfiles checked; 0 errors, 0 warnings, 0 badness; has taken 0.1 s ====================================================================================================================
```

**Comment by lsm5** [comment]
> Probably because I'm on CentOS Stream 9:
> 
> ```
> # rpm -qv rpmlint
> rpmlint-1.11-19.el9.noarch
> ```

I'm hoping we can ignore el9 warnings assuming Fedora is happy, unless it's causing any noticeable issues.

**Comment by sandrobonazzola** [comment]
Ok so I'm going to push a PR for using `%{_prefix}/lib/%{modulenames}`

**Comment by pypingou** [comment]
> I don't mind moving this to a different directory. But /usr/lib64 does not feel correct, perhaps /usr/share/qm?

`/usr/share/` sounded good to me, but I'm late to the party and thus won't get to pick the color of the shed :)

**Comment by rhatdan** [comment]
@alexlarsson WDYT?
