### ISSUE TITLE
`additional_store` demo workflow doesn't work 

### ISSUE THREAD

**Issue by sandrobonazzola** [containers/qm#143]
I'm following `additional_store` function in https://github.com/containers/qm/blob/main/demos/demo#L174 
for testing qemu-kvm as quadlet.

I created a `Dockerfile ` containing:
```dockerfile
FROM quay.io/centos/centos:stream9
RUN dnf -y swap --setopt=tsflags=nodocs centos-release centos-release-automotive && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Automotive && \
    dnf -y install --setopt=tsflags=nodocs --repofrompath auto-testing,https://buildlogs.centos.org/9-stream/automotive/x86_64/packages-main/ dbus-x11 qemu-kvm-core qemu-kvm-ui-dbus && \
    dnf clean all
```

and built it with:
```console
# podman --root /var/lib/shared build -t qemu-container .
```
It's showing up correctly:
```console
# podman --root /var/lib/shared images
REPOSITORY                TAG         IMAGE ID      CREATED         SIZE
localhost/qemu-container  latest      28da491b8315  13 minutes ago  295 MB
quay.io/centos/centos     stream9     7a8f9253940e  3 days ago      160 MB
```

Then I updated the `/etc/containers/systemd/qm.container` file adding:
```ini
Volume=/var/lib/shared:/var/lib/shared:ro
```

and executed
```console
# systemctl daemon-reload
# systemctl restart qm.service
```

The following command in the demo is: `podman exec qm podman images` but it doesn't show the images in the shared volume.
I tried:
```console
# podman exec qm podman --root /var/lib/shared images 
Error: opening database /var/lib/shared/libpod/bolt_state.db: open /var/lib/shared/libpod/bolt_state.db: permission denied
```

How can I make the shared image be available to the podman within the qm partition?

I think something is missing in the demo to make it working

**Comment by dougsland** [comment]
@sandrobonazzola I have heard you guys moved forward with QM, any pending tasks for this issue here? Still a blocker? Should we close?

**Comment by sandrobonazzola** [comment]
Yes, I think we can close this one.
