### ISSUE TITLE
re-enable EPEL Bodhi automation once RHEL 9.3 will GA

### ISSUE THREAD

**Issue by sandrobonazzola** [containers/qm#159]
EPEL Bodhi automation was disabled with commit 1cfd9786d41edd0f9d91bc433799c9460bfded3e .
Once podman >= 2:4.5 will be available in RHEL 9.3 we'll need to re-enable EPEL Bodhi automation and adjust `qm.spec` for requiring it everywhere.

**Comment by dougsland** [comment]
This should be fixed already, closing. Feel free to re-open.
