### ISSUE TITLE
Tests should use one image for control and nodeX

### ISSUE THREAD

**Issue by Yarboa** [containers/qm#164]
Looking here

https://github.com/containers/qm/blob/main/tests/e2e/lib/container#L40
It seems that each control/nodeX container creates its own image

podman images
localhost/node1        latest      c56be5754396  6 minutes ago   2.6 GB
localhost/control      latest      50f3fa0a8e30  12 minutes ago  2.07 GB

Consider using one test-base-image for control and nodeX

**Comment by rhatdan** [comment]
SGTM

**Comment by Yarboa** [comment]
Only issue I see using one ContainerFile is the extra ContainerFile.node"${nodeID}
We are adding some commands, so it blocks moving to one image
@dougsland 
Do you think it is better running only the commands on nodeN instead of using new image? 
https://github.com/containers/qm/blob/main/tests/e2e/lib/container#L99-#L116

MHO, it is shorter then downloading another 2G

**Comment by dougsland** [comment]
> Only issue I see using one ContainerFile is the extra ContainerFile.node"${nodeID} We are adding some commands, so it blocks moving to one image @dougsland Do you think it is better running only the commands on nodeN instead of using new image? https://github.com/containers/qm/blob/main/tests/e2e/lib/container#L99-#L116
> 
> MHO, it is shorter then downloading another 2G

sure thing, we need that. Today the logic works but is not fast enough.  :/

**Comment by Yarboa** [comment]
OK, I will work on it

**Comment by rhatdan** [comment]
Any update on this?

**Comment by Yarboa** [comment]
Yes, back from PTO

**Comment by Yarboa** [comment]
starting

**Comment by Yarboa** [comment]
Looking at images inside the vm 
[root@ibm-p8-kvm-03-guest-02 ~]# podman images
REPOSITORY                 TAG         IMAGE ID      CREATED            SIZE
localhost/base-test-image  latest      f72e12c525bd  About an hour ago  2.97 GB
quay.io/centos/centos      stream9     c54d0733008d  5 days ago         160 MB

There is one image already, 
But still checking to see if there is more to mprove
