### ISSUE TITLE
E2E: adapt the e2e code to new hirte naming (bluechi)

### ISSUE THREAD

**Issue by dougsland** [containers/qm#169]
The Hirte project has being renamed to BlueChi and we should adapt the E2E code to this change, see also:

bluechi: rename source code and build systems #460
https://github.com/containers/bluechi/pull/460

**Comment by sandrobonazzola** [comment]
Can you add some more descriptive text in the above description field? :-)

**Comment by dougsland** [comment]
> Can you add some more descriptive text in the above description field? :-)

Oh, I thought the title was enough, let me do it now. ;-)

**Comment by dougsland** [comment]
@rhatdan you are right, done. Closing.
