### ISSUE TITLE
test: Integrate the work already done from Edge/Tests to QM tests

### ISSUE THREAD

**Issue by dougsland** [containers/qm#213]
The scripts must be integrated with the approach described here: https://github.com/containers/qm/pull/212

Gitlab edge work: https://gitlab.com/redhat/edge/tests/base-image/-/tree/main/FFI

**Comment by dougsland** [comment]
Feel free to explore `git submodule`  if you guys would like to keep the gitlab tree or just bring the files. I would recommend sync with @Yarboa regarding files structure.

**Comment by dougsland** [comment]
Until https://github.com/containers/qm/pull/212 is done, fell free to test QM using the E2E tool: https://github.com/containers/qm/tree/main/tests/e2e

```
git clone http://github.com/containers/qm && cd qm/tests/e2e
 ./run-test-e2e
```

After that to see the isolation:

```
# podman ps

# podman exec -it control bash
or
# podman exec -it node1 bash

on node1 you can go inside the nested container (qm) using:
# node1> podman exec -it qm bash
```

Please let us know if you need any help to start looking to QM.

**Comment by Yarboa** [comment]
Please use this script for your setup
https://github.com/containers/qm/blob/main/tests/e2e/set-ffi-env-e2e
In case you need network, podman quadlet for network could be for help
PTAL https://www.redhat.com/sysadmin/multi-container-application-podman-quadlet

**Comment by dennisbrendel** [comment]
No promises, but I can look into actually doing this maybe this week.

I will then keep the git history of the test code when I integrate it here.

**Comment by Yarboa** [comment]
@dougsland I think we cam close this one
It all exist in other repo
https://gitlab.com/redhat/edge/tests/base-image/-/tree/main/FFI

**Comment by dougsland** [comment]
sure, thanks @Yarboa
