### ISSUE TITLE
e2e test is broken

### ISSUE THREAD

**Issue by Yarboa** [containers/qm#226]
Please refer recent gating results 
Error: no container with name or ID "qm" found: no such container
 
https://artifacts.dev.testing-farm.io/beb520f1-c367-4e13-a572-371f65e7c317/

**Comment by Yarboa** [comment]
I am trying to duplicate with clean vm, it will take me  some time

**Comment by Yarboa** [comment]
@dougsland 
podman build -f ContainerFile.node1 -t localhost/node:latest

Is failing here 
```
STEP 15/20: RUN /usr/share/qm/setup 2>&1 > /tmp/qm-setup.log || echo QM setup failed, please check /tmp/qm-setup.log.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
mount: /usr/lib/qm/rootfs/etc: permission denied.
QM setup failed, please check /tmp/qm-setup.log
```

**Comment by Yarboa** [comment]
so mount is failing 
mount: /usr/lib/qm/rootfs/etc: permission denied.

**Comment by rhatdan** [comment]
You need to run with `setup --skip-systemctl` since systemd is not running within the container.

**Comment by rhatdan** [comment]
Are there AVCs generated?

IE Does it work if you do `setenforce 0`.

If not then try

$ podman build --cap-add SYS_ADMIN /tmp/

**Comment by Yarboa** [comment]
Status still open
We are now in the nodeX container build 
since we we run the following in node1, we see the following 
```
journalctl -u qm.service
``` 

returns this 

> Oct 01 07:02:50 node1 podman[310]: 2023-10-01 07:02:50.10212604 +0000 UTC m=+0.073491345 container remove 527d1>
> Oct 01 07:02:50 node1 qm[310]: Error: crun: executable file `/sbin/init` not found in $PATH: No such file or di>
> Oct 01 07:02:50 node1 systemd[1]: qm.service: Main process exited, code=exited, status=127/n/a
> Oct 01 07:02:50 node1 systemd[1]: qm.service: Killing process 323 (conmon) with signal SIGKILL.
> Oct 01 07:02:50 node1 systemd[1]: qm.service: Killing process 326 (podman) with signal SIGKILL.
> Oct 01 07:02:50 node1 systemd[1]: qm.service: Killing process 330 (podman) with signal SIGKILL.
> Oct 01 07:02:50 node1 systemd[1]: qm.service: Killing process 333 (podman) with signal SIGKILL.
> Oct 01 07:02:50 node1 systemd[1]: qm.service: Killing process 334 (podman) with signal SIGKILL.
> Oct 01 07:02:50 node1 systemd[1]: qm.service: Killing process 335 (n/a) with signal SIGKILL.
> Oct 01 07:02:50 node1 systemd[1]: qm.service: Failed with result 'exit-code'.
> Oct 01 07:02:50 node1 systemd[1]: Failed to start qm.service.
> 

I assume the build is the issue, /me check

**Comment by Yarboa** [comment]
run container inside node1 is 
```
/usr/bin/podman run --privileged --name=qm --replace --rm --cgroups=split --tz=local --network=host --sdnotify=conmon -d --security-opt label=type:qm_t --security-opt label=filetype:qm_file_t --security-opt label=level:s0 --device=/dev/kvm --device=/dev/fuse --cap-drop=sys_resource --cap-add=all --read-only --read-only-tmpfs=false -v /etc/qm:/etc -v /var/qm:/var --pids-limit=-1 --security-opt label=nested --security-opt unmask=all --rootfs /usr/lib/qm/rootfs /usr/lib/systemd/systemd
```

Qm called with root /usr/lib/qm/rootfs is the ps container scope and there is no  /usr/lib/systemd/systemd inside the container

**Comment by Yarboa** [comment]
One more issue, when building the container 
once building the image, the following errors occur once setup is running 

> STEP 15/19: RUN /usr/share/qm/setup 2>&1 > /tmp/qm-setup.log || echo QM setup failed, please check /tmp/qm-setup.log.
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> mount: /usr/lib/qm/rootfs/etc: permission denied.
>

**Comment by rhatdan** [comment]
Looks to me like setup blew up and did not install systemd.

**Comment by Yarboa** [comment]
I assumes that systemd already installed by the container files 
But reading again README.md 

```
The QM will run its own version of systemd and Podman to isolate not only the applications and containers
```

**Comment by rhatdan** [comment]
Any AVC messages when you get permission denied?

**Comment by Yarboa** [comment]
OK, one more input
Was umount tmpfs while nodeX is running 
and then run the following command 
```
/usr/share/qm/setup
```
Container is up and running,
Some how storage was not created, 
The following extra line is the difference between node1 created by script and manual run 

shm on /var/lib/containers/storage/overlay-containers/8f742bff9017f2120b3ab252773c4c8d62563c11b1dc71937aee40a839405e79/userdata/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,size=64000k,inode64) 

This could be hint for the issue, no storage created 
And it brought me to this part
https://developers.redhat.com/blog/2019/08/14/best-practices-for-running-buildah-in-a-container

still searching

**Comment by Yarboa** [comment]
> Any AVC messages when you get permission denied?

Related to this 
c9s vm selinux status Permissive
```
getenforce 
Permissive
```

While running container run command inside node1

The following audit, appears 
```
type=BPF msg=audit(1696237885.275:8647): prog-id=1010 op=LOAD
type=SYSCALL msg=audit(1696237885.275:8647): arch=c000003e syscall=321 success=yes exit=8 a0=5 a1=7ffe1b928910 a2=90 a3=9500000000 items=0 ppid=252522 pid=252523 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=6 comm="3" exe="/" subj=unconfined_u:unconfined_r:spc_t:s0 key=(null)ARCH=x86_64 SYSCALL=bpf AUID="root" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
type=PROCTITLE msg=audit(1696237885.275:8647): proctitle=2F7573722F62696E2F6372756E002D2D6C6F672D666F726D61743D6A736F6E002D2D6C6F67002F72756E2F636F6E7461696E6572732F73746F726167652F6F7665726C61792D636F6E7461696E6572732F3533653663366634663861303565316631306139396235333331633733383537376333366161313631383639623937
type=BPF msg=audit(1696237885.291:8648): prog-id=1010 op=UNLOAD
```

**Comment by Yarboa** [comment]
> podman build --cap-add SYS_ADMIN /tmp/

Missed that, will give it a try
