### ISSUE TITLE
FFI tests should run on test setup similar to AutoSD

### ISSUE THREAD

**Issue by Yarboa** [containers/qm#233]
As a test maintainer i would like to have unified FFI testing setup for AutoSD and c9s qm tests

**Current test setp**
-- QM c9s image  
QM CI uses setup script, https://github.com/containers/qm/blob/main/tests/e2e/run-test-e2e

Host with at least two containers running,
Control and Node{NodeId}
- Control container has running bluechi-controller and at least one bluechi-agent services running
- Node{NodeID} container, there is bluechi-agent  service and qm service running
(QM service has another bluchi-agent service).

-- AutoSD image.
host service:
- bluechi-controller,
- bluechi-agent and
- qm service (bluechi-agent service in side qm container).

**Propose new test setup**
Create in QM repo new setup script that create  test setup closer to AutoSD setup

sample code complexity could be fine in FFI tests in PR #212

**Comment by Yarboa** [comment]
@dougsland @dennisbrendel

**Comment by dougsland** [comment]
Sure thing, anything closer to AutoSD is always good. One thing I was wondering here is, should we for example use Kickstart (Installer) to make vms and partitions for qm?

**Comment by dougsland** [comment]
@rhatdan ^

**Comment by dennisbrendel** [comment]
So you would go for a classical installation in a VM? It is anaconda that handles kickstart iirc.

We could also think of a Vagrant based setup or cloud-init, or just a preparation script.

**Comment by dougsland** [comment]
> So you would go for a classical installation in a VM? It is anaconda that handles kickstart iirc.

Discussed last week with @Yarboa:
- move `control` container to run on the `host` as `VM`
- remove the container `node1` 
- run `qm` as container and NOT as nested container inside node1

> We could also think of a Vagrant based setup or cloud-init, or just a preparation script.

Wouldn't kickstart fit better in the above scenario? @Yarboa @dennisbrendel 

/cc @rhatdan

**Comment by rhatdan** [comment]
SGTM
I like the idea of setting up /var/qm to run on a different partition.

**Comment by Yarboa** [comment]
Closing this one, 
#212 is a test running on the above test setup
