### ISSUE TITLE
Set `AllowedCPUs=` by detecting number of cpus on target system

### ISSUE THREAD

**Issue by lsm5** [containers/qm#24]
https://github.com/containers/qm/blob/1c0282f61b6a9de6c6ec27dc117467923c010325/qm.container#L2

This is currently hardcoded and can fail on systems which don't have enough cpus.

This can probably go into a post install script for the rpm.

**Comment by rhatdan** [comment]
Value should be 

```
$nproc=$(nproc)
$(expr $nproc / 2)"-"$(expr $nproc - 1)
6-11
```
