### ISSUE TITLE
setup script set QM bluechi agent.conf in old place

### ISSUE THREAD

**Issue by Yarboa** [containers/qm#248]
During the work on the following PR #245 
QM bluechi agent did not connect to bluechi-controller

PTAL in that fix
https://github.com/containers/qm/pull/245/files#diff-ed4cd590d534395a418d961acd614ebff97ed5889b9ca785094dd0a10d27863dR144

Need to move 
this 
RWETCFS="/etc/qm/" -> ${RWETCFS}/bluechi/bluechi-agent.d"

https://github.com/containers/qm/blob/main/setup#L15
It should be moved 
AGENTCONF=${RWETCFS}/bluechi/bluechi-agent.d/agent.conf"

**Comment by dougsland** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
SGTM
