### ISSUE TITLE
tests/FFI/memory: Remove redundant code

### ISSUE THREAD

**Issue by dennisbrendel** [containers/qm#282]
Currently https://github.com/containers/qm/blob/main/tests/e2e/tools/FFI/memory/ASIL/20_percent_memory_eat.c and https://github.com/containers/qm/blob/main/tests/e2e/tools/FFI/memory/QM/90_percent_memory_eat.c are almost completely identical.

They should be merged, so that the two binaries can be generated from the same sources.

**Comment by dennisbrendel** [comment]
Tracked in https://github.com/containers/qm/pull/279

**Comment by dougsland** [comment]
merged
