### ISSUE TITLE
tests/ffi/agent-flood/main.fmf: Description=bluechi-tester-X

### ISSUE THREAD

**Issue by dougsland** [containers/qm#302]
```
[Unit]
Description=bluechi-tester-X
```

```
[Container]
Image=dir:/var/lib/containers/registry/tools-ffi:latest
Exec=/root/tests/FFI/bin/bluechi-tester --url="tcp:host=localhost,port=842" \
     --nodename=bluechi-tester-X \
```

Could you please check if we can replace `bluechi-tester-X` with isn't `tester-${i}` ?

**Comment by pengshanyu** [comment]
Executed this test on a local VM and the results were as follows:

`[root@guest-02 ~]# cd /etc/qm/containers/systemd/
[root@guest-02 systemd]# ll
total 8
-rw-r--r--. 1 root root 303 Feb 29 20:35 bluechi-tester-1.container
-rw-r--r--. 1 root root 303 Feb 29 20:35 bluechi-tester-2.container


[root@guest-02 systemd]# cat bluechi-tester-1.container 
[Unit]
Description=bluechi-tester-1
After=local-fs.target

[Container]
Image=dir:/var/lib/containers/registry/tools-ffi:latest
Exec=/root/tests/FFI/bin/bluechi-tester --url="tcp:host=localhost,port=842"      --nodename=bluechi-tester-1      --numbersignals=11111111      --signal="JobDone"
Network=host


[root@guest-02 systemd]# cat bluechi-tester-2.container 
[Unit]
Description=bluechi-tester-2
After=local-fs.target

[Container]
Image=dir:/var/lib/containers/registry/tools-ffi:latest
Exec=/root/tests/FFI/bin/bluechi-tester --url="tcp:host=localhost,port=842"      --nodename=bluechi-tester-2      --numbersignals=11111111      --signal="JobDone"
Network=host`

**Comment by dougsland** [comment]
Thanks @pengshanyu, closing this one. One less in our queue.
