### ISSUE TITLE
update description in qm fedora packaging landing page

### ISSUE THREAD

**Issue by dougsland** [containers/qm#307]
https://copr.fedorainfracloud.org/coprs/rhcontainerbot/qm/

Change `installation instructions`

**Comment by Yarboa** [comment]
@dougsland 
https://copr.fedorainfracloud.org/coprs/rhcontainerbot/qm/

Done

**Comment by dougsland** [comment]
> @dougsland https://copr.fedorainfracloud.org/coprs/rhcontainerbot/qm/
> 
> Done

Thanks Yariv! Closing this one.
