### ISSUE TITLE
e2e/tier-0 tests is failing in setup

### ISSUE THREAD

**Issue by weiwang-linda** [containers/qm#310]
I encountered an issue with c9s.
 [ INFO  ] Creating quadlet container file: container-radio in node1 and moving it to container qm to start the quadlet service...
        Job for container-radio.service failed because the control process exited with error code.
        See "systemctl status container-radio.service" and "journalctl -xeu container-radio.service" for details.
        [ FAILED ] unable to start the quadlet service container-radio with exit code: 1

The container-radio service start failed from qm

Jan 17 01:26:17 node1 systemd[1]: Starting The sleep container...
Jan 17 01:26:17 node1 container-radio[59]: time="2024-01-17T01:26:17Z" level=warning msg="Failed to read /etc/containers/storage.conf toml: line 53 (last key \"storage.options.additionalimagestores\"): expected value but found \"Allows\" instead\n"
Jan 17 01:26:17 node1 container-radio[59]: time="2024-01-17T01:26:17Z" level=error msg="toml: line 53 (last key \"storage.options.additionalimagestores\"): expected value but found \"Allows\" instead"
Jan 17 01:26:17 node1 systemd[1]: container-radio.service: Main process exited, code=exited, status=1/FAILURE

It is broken grep here
If you update the containers.conf
to this
additionalimagestores = [
"/var/lib/shared",
]
all the other next till next session should stay commented

https://github.com/containers/qm/blob/c883d171c2d993206d6c48e73c1fc8d314699527/setup#L100-L104

So it is easy to reproduce since the origin file exist
ls -ltr /usr/lib/qm/rootfs/usr/share/containers/storage.conf
need to update correct regexp to give the fixed output

**Comment by Yarboa** [comment]
@weiwang-linda 
I think this sed is more safe to use 
-e '/additionalimages.*/a\"/var\/lib\/shared/\",'   from that one 
-e '/additionalimages.*/{n;s/.*/\"\/var\/lib\/shared\",/;}'

**Comment by Yarboa** [comment]
@dougsland It seems that bluechi has changed, tier-0 tests are failing

**Comment by Yarboa** [comment]
There has a change from 
ManagerHost -> ControllerAddress

Need to change e2e scripts
e "s/^#ManagerHost=/ManagerHost='"
