### ISSUE TITLE
Update ffi-tools links to eclipse/bluechi

### ISSUE THREAD

**Issue by Yarboa** [containers/qm#318]
Currently ffi-tools container 

use old bluechi link
https://gitlab.com/CentOS/automotive/container-images/ffi-tools/-/blob/main/Containerfile?ref_type=heads#L88

**Comment by engelmi** [comment]
@Yarboa I tried to solve this and opened this MR:
https://gitlab.com/CentOS/automotive/container-images/ffi-tools/-/merge_requests/13

**Comment by Yarboa** [comment]
@engelmi Adding JIRA label
@odra PTAL

**Comment by Yarboa** [comment]
Merged, by @odra  closing
