### ISSUE TITLE
centos9: qm.te:3:ERROR 'syntax error' at token 'container_use_ptys' on line 3613: #line 3

### ISSUE THREAD

**Issue by dougsland** [containers/qm#32]
1) My host: RHEL8
2) build + run CentOS9 container
3) Execute `make install` for later execute `setup`

Container:
```
# podman exec -it node /bin/bash
#node> cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

Executing make install:
```
# cd /tmp/qm
#qm> make install
go-md2man --in qm.8.md --out qm.8
make -f /usr/share/selinux/devel/Makefile qm.pp
make[1]: Entering directory '/tmp/qm'
Compiling targeted qm module
qm.te:3:ERROR 'syntax error' at token 'container_use_ptys' on line 3613:
#line 3
	container_use_ptys(qm_t)
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make[1]: *** [/usr/share/selinux/devel/include/Makefile:157: tmp/qm.mod] Error 1
make[1]: Leaving directory '/tmp/qm'
make: *** [Makefile:24: qm.pp] Error 2```

**Comment by dougsland** [comment]
adding @rhatdan into the loop

**Comment by rhatdan** [comment]
Ok this looks like container-selinux is not updated.

Could you make sure container-selinux is installed?

dnf -y install container-selinux

**Comment by rhatdan** [comment]
$ grep BuildRequires qm.spec.rpkg 
BuildRequires: go-md2man
BuildRequires: container-selinux
BuildRequires: make
BuildRequires: git-core
BuildRequires: pkgconfig(systemd)
BuildRequires: selinux-policy >= %_selinux_policy_version
BuildRequires: selinux-policy-devel >= %_selinux_policy_version

**Comment by dougsland** [comment]
Thanks Dan. It seems improved but still missing something:
```
[root@control qm]# make install
go-md2man --in qm.8.md --out qm.8
make -f /usr/share/selinux/devel/Makefile qm.pp
make[1]: Entering directory '/root/qm'
Compiling targeted qm module
qm.te:3:ERROR 'unknown class user_namespace' at token ';' on line 4377:
	allow qm_t self:user_namespace all_user_namespace_perms;
#line 3
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make[1]: *** [/usr/share/selinux/devel/include/Makefile:157: tmp/qm.mod] Error 1
make[1]: Leaving directory '/root/qm'
make: *** [Makefile:24: qm.pp] Error 2
```

```
# rpm -qa | grep selinux-policy
selinux-policy-38.1.12-1.el9.noarch
selinux-policy-targeted-38.1.12-1.el9.noarch
selinux-policy-devel-38.1.12-1.el9.noarch

# rpm -qa | grep container-selinux
container-selinux-2.211.0-1.el9.noarch

[root@control qm]# dnf update -y
Last metadata expiration check: 0:11:05 ago on Sun May  7 12:17:39 2023.
Dependencies resolved.
Nothing to do.
Complete!

# cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

**Comment by rhatdan** [comment]
Yes @lsm5 is filtering that line out on centos9.  The version of selinux-policy in centos9/rhel9 does not enforce user_namespace yet.  So remove that line and you should be all set.

**Comment by lsm5** [comment]
@dougsland been a while, hope you're well. selinux-policy on c9s is quite a few minor versions away than the one in fedora 38/ rawhide. Hopefully it'll get updated soon. 

Closing, please reopen if anything.

**Comment by dougsland** [comment]
for reference:

```
qm> sed -i '/user_namespace/d' qm.if
qm> make install
qm> setup
```

**Comment by rhatdan** [comment]
$ seinfo -c | grep user_namespace
   user_namespace
or
```
 seinfo -cuser_namespace

Classes: 1
   user_namespace
```
Sadly this does not blow up if user_namespace does not exist.
``` 
$ seinfo -cuser_namespace1

Classes: 0
```

**Comment by rhatdan** [comment]
```
$ sesearch -A -c user_namespace1
user_namespace1 is not a valid class
podman (build) $ echo $?
1
```

These packages are available in setools-console

**Comment by rhatdan** [comment]
This should work.
```
$ stat /sys/fs/selinux/class/user_namespace > /dev/null 
$ stat /sys/fs/selinux/class/user_namespace1 > /dev/null 
stat: cannot statx '/sys/fs/selinux/class/user_namespace1': No such file or directory 
```

**Comment by lsm5** [comment]
> This should work.
> 
> ```
> $ stat /sys/fs/selinux/class/user_namespace > /dev/null 
> $ stat /sys/fs/selinux/class/user_namespace1 > /dev/null 
> stat: cannot statx '/sys/fs/selinux/class/user_namespace1': No such file or directory 
> ```

@rhatdan you meant stick that into Makefile, right? or is it possible to handle distro conditionals in the `*.if` files itself?

**Comment by dougsland** [comment]
@lsm5 @rhatdan we are a `rpm` shop and it's fine to do in the `spec` file. However, yes, I was doing manually for testing CI/CD should we also move this to `setup` instead?  Helps people with CentOS9 building from main branch. On top of that, will this `sed` be required in other distros like Ubuntu/Arch/Alpine/3rd Vendors? Feel free to re-open this one and assign to me.

**Comment by rhatdan** [comment]
Yes I have no problem with adding the stat line into the Makefile, for now, since we have no idea if the selinux-policy with support for user-namespace class will make it into RHEL9/Centos9.

**Comment by lsm5** [comment]
> @lsm5 @rhatdan we are a `rpm` shop and it's fine to do in the `spec` file. However, yes, I was doing manually for testing CI/CD should we also move this to `setup` instead? Helps people with Fedora/CentOS9 building from main branch. On top of that, will this `sed` be required in other distros like Ubuntu/Arch/Alpine/3rd Vendors to support multi arch/distro? Feel free to re-open this one and assign to me.

I guess it's no use on distros that don't use selinux. So, would be good to have it in makefile either way.

Just to make sure I understand your usage of `setup`, are you talking about the setup script here or the `%setup` stage in rpmbuild ? The `setup` script comes later on in the process and is only done manually post-install. We'll need something prior to the qm module build step. @rhatdan can correct me.

Either way, I still feel Makefile itself is ideal, so other distros could also benefit.

**Comment by rhatdan** [comment]
Yes in Makefile is correct place.

**Comment by rhatdan** [comment]
That way it can be built.  We probably need to add some SELinux checks to make sure that qm can work on disabled or non SELinux systems.

**Comment by dougsland** [comment]
Got resolved by @rhatdan  in a PR.
