### ISSUE TITLE
spec: replace buildrequirement: vsomeip3-selinux to requires

### ISSUE THREAD

**Issue by dougsland** [containers/qm#324]
If I understood correctly, it's not required for the build but for usage.

**Comment by Yarboa** [comment]
@dougsland
The solution for that, since we would like to push to centos-stream to have conditional to build
sikilar to this
https://github.com/eclipse-bluechi/bluechi/blob/44e15cc0aafe9954f86e7c14cf008f04dac600b2/build-scripts/build-rpm.sh#L13

WITH vsomeip-3-selinux for the build

**Comment by Yarboa** [comment]
@dougsland need to add build README :)
