### ISSUE TITLE
FFi tool containers. missing arm64 manifest

### ISSUE THREAD

**Issue by Yarboa** [containers/qm#328]
Resolves #333 

Running tests on ARM machines

Return the following:

 podman run -it quay.io/centos-sig-automotive/ffi-tools:latest shell
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
Error: crun: executable file `shell` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found

**Comment by rhatdan** [comment]
Is there an ffi-tools image built for arm?

**Comment by Yarboa** [comment]
> Is there an ffi-tools image built for arm?

In progress, we are testing qm also on arm

**Comment by Yarboa** [comment]
Thanks @odra
