### ISSUE TITLE
Add option in test to work with c9s release

### ISSUE THREAD

**Issue by Yarboa** [containers/qm#334]
Currently QM/Bluechi rpms exist in AutoSD repo,

Tests should include an option not to work with copr

To verify it is working,
Run TMT with PACKIT_COPR_PROJECT=release 

I assume AutoSD should be enabled in case PACKIT_COPR_PROJECT=release

**Comment by Yarboa** [comment]
@pengshanyu I think this one is already Done

**Comment by pengshanyu** [comment]
@Yarboa Thanks for this info.
I've tried with PACKIT_COPR_PROJECT=release and --context distro=c9s, and the result seems correct.

**Comment by dougsland** [comment]
> @Yarboa Thanks for this info. I've tried with PACKIT_COPR_PROJECT=release and --context distro=c9s, and the result seems correct.

@Yarboa @pengshanyu can we close this one?

**Comment by Yarboa** [comment]
@dougsland Not yet, Iassume @pengshanyu need to propose PR
