### ISSUE TITLE
Create qm sanity tests 

### ISSUE THREAD

**Issue by pbrilla-rh** [containers/qm#342]
We have several test cases for FFI, but we are missing some basic/simple sanity tests for qm, if it is installed properly and/or if environment started successfully

Adding Note:
I would add updating tiear-0 test to verify through bluchictl

If there are 2 bluechi nodes connected to controller from host and QM it means that QM service is up and podman container is running

**Comment by dougsland** [comment]
@pengshanyu are you interested in this one? I am sure @pbrilla-rh and I can share more info if needed. Assigning to you for now.

**Comment by Yarboa** [comment]
@pengshanyu 

I assume tier-0 tests which run on different scenario in the pipeline sould run also with the 
    filter: tag:ffi of /plans/e2e/ffi
    
Please use this test, tests/qm-unit-files/main.fmf  

that run in different test setups , you can manipulate the same  
like here 
/tests/qm-connectivity/tier0
/tests/qm-connectivity/tier1
/tests/qm-connectivity/ffi


Whenever FFI filter is selected, qm-connectivity, with some ENV changes will verify ffi setup

**Comment by pengshanyu** [comment]
@Yarboa Thank you for sharing.

**Comment by pengshanyu** [comment]
Hi @Yarboa, it seems that the tier0 test mentioned by Pavol is different from the one you mentioned in the comment above. What test cases do we want tier0 to include? Thanks.

**Comment by Yarboa** [comment]
Correct this repo evolved within time
Could be that tier-0 tests running in that gate, should be renamed, I think it is not so important for now that we have the FFI test environemt


But, I could think of tier-0 tests as per that one:

1) Verify qm is up and running
systemctl is-active qm
2) Verify bluechi nodes are connected 
bluechictl status,
2 nodes connected
3) podman run and exec container inside qm with service file
4) /var partition exist

**Comment by pengshanyu** [comment]
@Yarboa @pbrilla-rh I named the sanity test to tier-0, but there are also tier-0 tests in `qm-connectivity` and `qm-unit-files`, how should they be renamed or do we want them to be tier-0 along with the sanity tests?
