### ISSUE TITLE
The bluechi-selinux package requires policycoreutils-python-utils

### ISSUE THREAD

**Issue by alexlarsson** [containers/qm#350]
This pulls in python3 into the automotive image if the bluechi-selinux package is installed. This dependency is not needed by any other selinux policy, so it should not be needed for this one.

**Comment by dougsland** [comment]
> This pulls in python3 into the automotive image if the bluechi-selinux package is installed. This dependency is
> not needed by any other selinux policy, so it should not be needed for this one.

@alexlarsson Should we remove from bluechi.spec instead of qm (in QM there is no such requirement) ? 
https://github.com/eclipse-bluechi/bluechi/blob/main/bluechi.spec.in#L151
https://github.com/eclipse-bluechi/bluechi/blob/main/bluechi.spec.in#L152

**Comment by alexlarsson** [comment]
Yeah, that makes sense. Not sure why I filed this here...

**Comment by mwperina** [comment]
We require `policy-coreutils-python` package in bluechi, because we are using semanage in `post*` RPM sections:

```
$ sudo dnf repoquery -q --whatprovides /usr/sbin/semanage
policycoreutils-python-utils-0:3.5-1.fc38.noarch
```

https://github.com/eclipse-bluechi/bluechi/blob/main/bluechi.spec.in#L167-L189

Not sure if the same functionality can be achieved with tools provided in `policy-coreutils` package ...

@engelmi

**Comment by mwperina** [comment]
> We require `policy-coreutils-python` package in bluechi, because we are using semanage in `post*` RPM sections:
> 
> ```
> $ sudo dnf repoquery -q --whatprovides /usr/sbin/semanage
> policycoreutils-python-utils-0:3.5-1.fc38.noarch
> ```
> 
> https://github.com/eclipse-bluechi/bluechi/blob/main/bluechi.spec.in#L167-L189
> 
> Not sure if the same functionality can be achieved with tools provided in `policy-coreutils` package ...
> 
> @engelmi

Or we would need to get rid of hirte upgrade remains in the spec in bluechi 0.8

**Comment by alexlarsson** [comment]
@mwperina Hmm, we only recently got rid of this python dependency in container-selinux: https://issues.redhat.com/browse/RHEL-18316
I really don't want to add it back via bluechi. If container-selinux can do without, surely bluechi can?

**Comment by alexlarsson** [comment]
@rhatdan We need some selinux help here.

**Comment by alexlarsson** [comment]
Note: Currently bluechi-selinux is not in the automotive images, due to it being a weak dep, and the manifests disable weak deps. I don't want to add it, because it then adds python to the qm-minimal image, which we don't want to have.

**Comment by engelmi** [comment]
Yes, probably @rhatdan is the only one who knows. 
Would it be sufficient to only require `policycoreutils-python-utils` on build?

**Comment by alexlarsson** [comment]
> Yes, probably @rhatdan is the only one who knows. Would it be sufficient to only require `policycoreutils-python-utils` on build?

No, currently the post install scripts calls semanage, which is in policycoreutils-python-utils. I think we need to somehow avoid this.

**Comment by rhatdan** [comment]
Can we just eliminate the lines about ports.  `semanage port` This is pulling in the policycoreutils-python package.

We should just loosen the policy and allow bluechi to use all ports.  Perhaps add a boolean and just turn this on for RHIVOS.

**Comment by alexlarsson** [comment]
Yeah, that seems like a good enough solution for now.

**Comment by engelmi** [comment]
Since this is an issue in BlueChi, I opened https://github.com/eclipse-bluechi/bluechi/issues/836 and would close this issue.
@dougsland Could you close this issue? It seems I don't have permissions to do it.
