### ISSUE TITLE
still valid comment? FIXME: oom killer not triggerd for qm processes

### ISSUE THREAD

**Issue by dougsland** [containers/qm#360]
https://github.com/containers/qm/blob/0c3420a8bd336a1c43c9ee715cf6d532417275ce/tests/ffi/common/prepare.sh#L22-L26

**Comment by dougsland** [comment]
@Yarboa please correct me if I am wrong, we talked another day about this one and this issue was gone with a kernel update. Could you please confirm?

**Comment by Yarboa** [comment]
It was not triggered on RideSX SoC, it was fixed already
Anyway, i think you should use here script variable with default 
OOMScoreAdjust=1000

**Comment by dougsland** [comment]
> It was not triggered on RideSX SoC, it was fixed already Anyway, i think you should use here script variable with default OOMScoreAdjust=1000

Ok, I will open an issue for that.
