### ISSUE TITLE
FFI: create a test case for executing sysctl inside nested container running on top of QM

### ISSUE THREAD

**Issue by dougsland** [containers/qm#370]
See: https://github.com/containers/qm/tree/main/tests/e2e/tools/FFI/sysctl

**Comment by dougsland** [comment]
cc @pbrilla-rh

**Comment by weiwang-linda** [comment]
With tft-cli, it is failed since file "set-ffi-env-e2e" using dnf as package management, but the qm-minimal using rpm-ostree as package management.
https://artifacts.dev.testing-farm.io/e5b24a5a-7f16-4cfc-8993-24522fdfd75e/
Looking up the https://autosd.sig.centos.org/AutoSD-9/nightly/ , qm-minimal hasn't non-ostree compose.

**Comment by dougsland** [comment]
> With tft-cli, it is failed since file "set-ffi-env-e2e" using dnf as package management, but the qm-minimal using rpm-ostree as package management. https://artifacts.dev.testing-farm.io/e5b24a5a-7f16-4cfc-8993-24522fdfd75e/ Looking up the https://autosd.sig.centos.org/AutoSD-9/nightly/ , qm-minimal hasn't non-ostree compose.

Please let me know if you need any help.

**Comment by weiwang-linda** [comment]
> > With tft-cli, it is failed since file "set-ffi-env-e2e" using dnf as package management, but the qm-minimal using rpm-ostree as package management. https://artifacts.dev.testing-farm.io/e5b24a5a-7f16-4cfc-8993-24522fdfd75e/ Looking up the https://autosd.sig.centos.org/AutoSD-9/nightly/ , qm-minimal hasn't non-ostree compose.
> 
> Please let me know if you need any help.

Hi @dougsland, good day! Thanks for your reply during your vocation. I think I need a regular compose now, but I don't know how to find it. All of the AMI_info_* files belong to ostree.  Let me ask toolchain or other related teams about this. Have a good holiday!
