### ISSUE TITLE
FFI: create a test plan for SCHED_DEADLINE

### ISSUE THREAD

**Issue by dougsland** [containers/qm#377]
Use the tool provided via #376 to create a test plan integrated to FFI-tools (https://gitlab.com/CentOS/automotive/container-images/ffi-tools).

See-Also: #376 #375

**Comment by pengshanyu** [comment]
filed a [MR](https://github.com/containers/qm/pull/453) to update the makefile

**Comment by pengshanyu** [comment]
filed a [MR](https://gitlab.com/CentOS/automotive/container-images/ffi-tools/-/merge_requests/30) to add it to the ffi-tools container image

**Comment by pengshanyu** [comment]
Filed a [PR](https://github.com/containers/qm/pull/455) to add tmt test case
