### ISSUE TITLE
qm.spec issue with podman dependency

### ISSUE THREAD

**Issue by alexlarsson** [containers/qm#379]
This here:
https://gitlab.com/CentOS/automotive/rpms/qm/-/blob/automotive_sig/qm.spec?ref_type=heads#L81
```
%if %{with podman_45}
Requires: podman >= %{podman_epoch}:4.5
%endif
```
Is wrong. If with_podman_45 is false, then there is no dependency at all on podman, which means podman will not be installed and the image breaks.

**Comment by dougsland** [comment]
merged
