### ISSUE TITLE
tests: CI/CD pipeline (tmt) - make sure nested containers work via QM

### ISSUE THREAD

**Issue by dougsland** [containers/qm#405]
As soon a new patch arrives for review, we need to trigger a test to make sure QM is executing well the **nested container via podman**.  

The example below are for manual steps:
```
git clone https://gitlab.com/CentOS/automotive/sample-images.git
pushd osbuild-manifests/
    make cs9-qemu-qm-minimal-regular.x86_64.qcow2
    ./runvm --nographics ./cs9-qemu-qm-minimal-regular.x86_64.qcow2

    user: root
    pass: password
    [root@localhost ~]# podman exec -it qm bash
    bash-5.1#  podman run -it --name fedora fedora  /bin/bash
    bash-5.1# podman ps
    exit
    exit
 (CTRC a-C -> quit) - to exit from qemu emulator 
popd
```

**Comment by dougsland** [comment]
cc @pbrilla-rh

**Comment by dougsland** [comment]
@RakeshMK90 mentioned that maybe this one already running in our tests?  @nsednev @pengshanyu are you aware I don't recall.

**Comment by Yarboa** [comment]
IIRC, most of the tests uses nested containers

**Comment by nsednev** [comment]
This issue should be closed as its covered by the test I wrote.
