### ISSUE TITLE
Modify qm quadlet file should be done through drop-in systemd files

### ISSUE THREAD

**Issue by Yarboa** [containers/qm#473]
This commented out part should be deleted

https://github.com/containers/qm/pull/472
Once adding doc for tests, "how to update qm quadlet file"

Assume one would like to expose port inside qm network
cat /etc/containers/systemd/qm.container.d/10-openport.conf  
[Container]
ExposeHostPort=842

Once running /usr/lib/systemd/system-generators/podman-system-generator --dryrun
the output should indicate reading qm quadlet updates from drop-in dir

```
quadlet-generator[4450]: Loading source unit file /usr/share/containers/systemd/qm.container
quadlet-generator[4450]: Loading source drop-in file /etc/containers/systemd/qm.container.d/10-openport.conf
```
systemd drop-in files are enabled in podman5

**Comment by dougsland** [comment]
@Yarboa should we close this one?

**Comment by Yarboa** [comment]
No, adding readme
