### ISSUE TITLE
tests/ffi/qm-oom-score-adj is failing

### ISSUE THREAD

**Issue by pengshanyu** [containers/qm#576]
The error message found is as follows:

```
Error: OCI runtime error: crun: the requested cgroup controller `pids` is not available
Error: ffi-qm container failed to start. Status: created
```

**Comment by pengshanyu** [comment]
Sure.

**Comment by giuseppe** [comment]
is it a flake or does it happen every time?

I've tried opening a PR with some debugging statements but the CI job was successful: https://github.com/containers/qm/pull/578

**Comment by pengshanyu** [comment]
Hi @giuseppe, thanks for the test, I'll ping you directly.

**Comment by pengshanyu** [comment]
I tried to run the test again and found that if I run `qm-oom-score-adj` alone it will pass, but if I run it with other test cases (under /tests/ffi), it will fail.

**Comment by pengshanyu** [comment]
Found the issue,  it was caused by the cleanup steps, will fix it.

**Comment by pengshanyu** [comment]
The fix works, the failure that occurred later were not caused by this test case itself.
