### ISSUE TITLE
[Fedora] Create a test for setup script

### ISSUE THREAD

**Issue by dougsland** [containers/qm#642]
Verify tmt flow is working on CloudBase Fedora 41

**Comment by Yarboa** [comment]
Working on it manually related to #647

**Comment by Yarboa** [comment]
Applied this change [p0.log](https://github.com/user-attachments/files/17668112/p0.log)

Now setup script is failing on that 
```
 dnf -y install --releasever=41 --installroot /usr/lib/qm/rootfs selinux-policy-targeted podman systemd bluechi-agent procps-ng iptables-nft jq
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
No match for argument: selinux-policy-targeted
No match for argument: podman
No match for argument: systemd
No match for argument: bluechi-agent
No match for argument: procps-ng
No match for argument: iptables-nft
No match for argument: jq
No repositories were loaded from the installroot. To use the configuration and repositories of the host system, pass --use-host-config.

```

**Comment by dougsland** [comment]
Solved by me and @Yarboa via: https://github.com/containers/qm/commit/c409c8bde538f99eec8b3bed37c0fd6f93914d78 and https://github.com/containers/qm/commit/c409c8bde538f99eec8b3bed37c0fd6f93914d78

**Comment by dougsland** [comment]
Maybe @Yarboa  will have more patches with improvements in the future.
