### ISSUE TITLE
error: %changelog entries must start with *

### ISSUE THREAD

**Issue by dougsland** [containers/qm#85]
CI is failing and showing this one:

Complete!
Finish: build setup for qm-0.4.2-1.20230611184105946704.pr83.25.gc293cec.el9.src.rpm
Start: rpmbuild qm-0.4.2-1.20230611184105946704.pr83.25.gc293cec.el9.src.rpm
error: %changelog entries must start with *

^^ here
@pypingou @lsm5  is there a way to workaround this one?

**Comment by dougsland** [comment]
Looks like @pypingou  was involved in this feature, I see his name here and others places:
https://fedoraproject.org/wiki/Changes/rpm_level_auto_release_and_changelog_bumping

**Comment by dougsland** [comment]
Here the autochangelog:
```
%changelog
%autochangelog
```

**Comment by pypingou** [comment]
Note that the rpmautospec doc is at: https://docs.pagure.org/fedora-infra.rpmautospec/index.html

**Comment by lsm5** [comment]
https://github.com/containers/podman/blob/main/rpm/podman.spec#L418-L424 .. maybe that helps.

**Comment by Yarboa** [comment]
@pypingou https://download.copr.fedorainfracloud.org/results/rhcontainerbot/packit-builds/centos-stream-9-x86_64/06063506-qm/builder-live.log.gz

**Comment by Yarboa** [comment]
> Note that the rpmautospec doc is at: https://docs.pagure.org/fedora-infra.rpmautospec/index.html

@pypingou https://download.copr.fedorainfracloud.org/results/rhcontainerbot/packit-builds/centos-stream-9-x86_64/06063506-qm/builder-live.log.gz

**Comment by dougsland** [comment]
@lsm5 nop but thanks for sharing. I am going to close this one, it's not really a bug in the software, it's rpmlint message only. If someone has time to investigate can re-open.
