### ISSUE TITLE
e2e: add support to dualstack

### ISSUE THREAD

**Issue by dougsland** [containers/qm#87]
1. create a network with dual stack 
```
 podman network create --ipv6 --gateway fd00::1:8:1 --subnet fd00::1:8:0/112 --gateway 10.90.0.1 --subnet 10.90.0.0/16 podman1
```

2. change the script to use this new network:
```
diff --git a/tests/e2e/lib/container b/tests/e2e/lib/container
index 129dc57..1b620ba 100644
--- a/tests/e2e/lib/container
+++ b/tests/e2e/lib/container
@@ -58,6 +58,7 @@ podman images failed! name: ${container_name}"
     # Execute the container
     eval "$(podman run -d \
                 --privileged \
+               --network podman1 \
                 --name "${container_name}" \
                 --hostname "${container_name}" \
                 "${IMAGE_ID}" 1> /dev/null
```

3. Make sure it works in TMT and Github Actions

See also: https://github.com/containers/hirte/pull/348

**Comment by rhatdan** [comment]
I am not sure what the idea here is?  Why didn't you open this as a PR?

**Comment by dougsland** [comment]
> I am not sure what the idea here is? Why didn't you open this as a PR?

Today e2e is only ipv4, would be nice to support both. However, I opened this one to explore this idea as it might be more than what I investigated as it's a virtual CI env via github actions/TmT.   :/
